// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZG0hRzM6ycQxWT5cCUtVQTHFEjLujFH0',
    appId: '1:825357754795:web:fbbf5ba34f6a011d82b2ee',
    messagingSenderId: '825357754795',
    projectId: 'logisticss-1ef6c',
    authDomain: 'logisticss-1ef6c.firebaseapp.com',
    storageBucket: 'logisticss-1ef6c.appspot.com',
    measurementId: 'G-YJ79XC8499',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZeOcg5v5sImBIDA6GjJCE14oPFUcMPbI',
    appId: '1:825357754795:android:4299f7abb8c1a52c82b2ee',
    messagingSenderId: '825357754795',
    projectId: 'logisticss-1ef6c',
    storageBucket: 'logisticss-1ef6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6024SM1qiMRzOxA72UrIP1UjDh7IUdSQ',
    appId: '1:825357754795:ios:384c90070620866d82b2ee',
    messagingSenderId: '825357754795',
    projectId: 'logisticss-1ef6c',
    storageBucket: 'logisticss-1ef6c.appspot.com',
    iosBundleId: 'com.example.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6024SM1qiMRzOxA72UrIP1UjDh7IUdSQ',
    appId: '1:825357754795:ios:3d711a0a9703571782b2ee',
    messagingSenderId: '825357754795',
    projectId: 'logisticss-1ef6c',
    storageBucket: 'logisticss-1ef6c.appspot.com',
    iosBundleId: 'com.example.customer.RunnerTests',
  );
}
